[phases.setup]
nixPkgs = ["nodejs", "python311", "python311Packages.pip"]

[phases.install]
cmds = [
  "pnpm install",
  "pnpm run build",
  "cd pizzaz_server_python && pip install -r requirements.txt"
]

[start]
cmd = "cd pizzaz_server_python && python main.py"